version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always

  frontend:
    build:
      context: "./Chat Application"
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
